import "./globals.css";
import Header from "@/app/(components)/Header";
import Footer from "@/app/(components)/Footer";
import { AppContextProvider } from "@/context/appContext";
import RootStyles from "./RootStyles";

export const metadata = {
  title: "WebxCell",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <Header />
          <RootStyles />
          {children}
          <Footer />
        </AppContextProvider>
      </body>
    </html>
  );
}
